In [112]:
#import libraries

import pandas as pd
import numpy as np
import re

from getpass import getpass
import sqlalchemy as alch 
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [113]:
artworks = pd.read_csv('../data_MoMa/artworks.csv')
artworks.head()

,Artwork ID,Title,Artist ID,Name,Date,Medium,Dimensions,Acquisition Date,Credit,Catalogue,...,Classification,Object Number,Diameter (cm),Circumference (cm),Height (cm),Length (cm),Width (cm),Depth (cm),Weight (kg),Duration (s)
0,2,"Ferdinandsbrücke Project, Vienna, Austria, Ele...",6210,Otto Wagner,1896,Ink and cut-and-pasted painted pages on paper,"19 1/8 x 66 1/2"" (48.6 x 168.9 cm)",1996-04-09,Fractional and promised gift of Jo Carole and ...,Y,...,Architecture,885.1996,NaN,NaN,48.6000,NaN,168.9000,NaN,NaN,NaN
1,3,"City of Music, National Superior Conservatory ...",7470,Christian de Portzamparc,1987,Paint and colored pencil on print,"16 x 11 3/4"" (40.6 x 29.8 cm)",1995-01-17,Gift of the architect in honor of Lily Auchinc...,Y,...,Architecture,1.1995,NaN,NaN,40.6401,NaN,29.8451,NaN,NaN,NaN
2,4,"Villa near Vienna Project, Outside Vienna, Aus...",7605,Emil Hoppe,1903,"Graphite, pen, color pencil, ink, and gouache ...","13 1/2 x 12 1/2"" (34.3 x 31.8 cm)",1997-01-15,Gift of Jo Carole and Ronald S. Lauder,Y,...,Architecture,1.1997,NaN,NaN,34.3000,NaN,31.8000,NaN,NaN,NaN
3,5,"The Manhattan Transcripts Project, New York, N...",7056,Bernard Tschumi,1980,Photographic reproduction with colored synthet...,"20 x 20"" (50.8 x 50.8 cm)",1995-01-17,Purchase and partial gift of the architect in ...,Y,...,Architecture,2.1995,NaN,NaN,50.8000,NaN,50.8000,NaN,NaN,NaN
4,6,"Villa, project, outside Vienna, Austria, Exter...",7605,Emil Hoppe,1903,"Graphite, color pencil, ink, and gouache on tr...","15 1/8 x 7 1/2"" (38.4 x 19.1 cm)",1997-01-15,Gift of Jo Carole and Ronald S. Lauder,Y,...,Architecture,2.1997,NaN,NaN,38.4000,NaN,19.1000,NaN,NaN,NaN

In [114]:
#check for duplicate rows
artworks.duplicated().sum()

0

In [115]:
#drop unnecessary columns
artworks.drop(columns = ['Catalogue', 'Diameter (cm)', 'Circumference (cm)', 'Height (cm)',
                         'Length (cm)', 'Width (cm)', 'Depth (cm)', 'Weight (kg)', 'Duration (s)'], inplace=True)

In [116]:
artworks.head()

,Artwork ID,Title,Artist ID,Name,Date,Medium,Dimensions,Acquisition Date,Credit,Department,Classification,Object Number
0,2,"Ferdinandsbrücke Project, Vienna, Austria, Ele...",6210,Otto Wagner,1896,Ink and cut-and-pasted painted pages on paper,"19 1/8 x 66 1/2"" (48.6 x 168.9 cm)",1996-04-09,Fractional and promised gift of Jo Carole and ...,Architecture & Design,Architecture,885.1996
1,3,"City of Music, National Superior Conservatory ...",7470,Christian de Portzamparc,1987,Paint and colored pencil on print,"16 x 11 3/4"" (40.6 x 29.8 cm)",1995-01-17,Gift of the architect in honor of Lily Auchinc...,Architecture & Design,Architecture,1.1995
2,4,"Villa near Vienna Project, Outside Vienna, Aus...",7605,Emil Hoppe,1903,"Graphite, pen, color pencil, ink, and gouache ...","13 1/2 x 12 1/2"" (34.3 x 31.8 cm)",1997-01-15,Gift of Jo Carole and Ronald S. Lauder,Architecture & Design,Architecture,1.1997
3,5,"The Manhattan Transcripts Project, New York, N...",7056,Bernard Tschumi,1980,Photographic reproduction with colored synthet...,"20 x 20"" (50.8 x 50.8 cm)",1995-01-17,Purchase and partial gift of the architect in ...,Architecture & Design,Architecture,2.1995
4,6,"Villa, project, outside Vienna, Austria, Exter...",7605,Emil Hoppe,1903,"Graphite, color pencil, ink, and gouache on tr...","15 1/8 x 7 1/2"" (38.4 x 19.1 cm)",1997-01-15,Gift of Jo Carole and Ronald S. Lauder,Architecture & Design,Architecture,2.1997

In [117]:
#extract date with regex, to get a clean year. first 4 digits only, create new column 'Year'

artworks['Year'] = artworks['Date'].str.extract('(\d{4})')

In [118]:
#check for null values
artworks.isna().sum()

Artwork ID              0
Title                  62
Artist ID            1460
Name                 1460
Date                 2312
Medium              11919
Dimensions          11463
Acquisition Date     5463
Credit               3070
Department              0
Classification          0
Object Number           0
Year                 3451
dtype: int64

In [119]:
#check how many artists in the df
artworks['Name'].value_counts()

Name
Eugène Atget                5050
Louise Bourgeois            3318
Ludwig Mies van der Rohe    2566
Unknown photographer        1575
Jean Dubuffet               1435
                            ...
Philip von Schantz             1
Hubert Kiecol                  1
Alberico Morena                1
Jeffrey Ingram Stone           1
Ely Ramen                      1
Name: count, Length: 13530, dtype: int64

In [120]:
#check how many classifications in the df
artworks['Classification'].value_counts()

Classification
Print                             30807
Photograph                        29909
Illustrated Book                  26160
Drawing                           11735
Design                            11223
Mies van der Rohe Archive          3331
Architecture                       2947
Video                              2363
Film                               2292
Painting                           2270
Sculpture                          1669
Multiple                           1030
(not assigned)                     1029
Frank Lloyd Wright Archive          785
Periodical                          741
Installation                        596
Work on Paper                       436
Audio                               429
Media                               343
Ephemera                             89
Textile                              33
Performance                          24
Collage                               9
Photography Research/Reference        4
Software                              3
Film (object)                         3
Furniture and Interiors               1
Product Design                        1
Name: count, dtype: int64

In [121]:
#check how many departments in the df
artworks['Department'].value_counts()

Department
Prints & Illustrated Books               60128
Photography                              29161
Architecture & Design                    18269
Drawings                                 11027
Painting & Sculpture                      3806
Film                                      3088
Media and Performance Art                 2627
Fluxus Collection                         2135
Architecture & Design - Image Archive       21
Name: count, dtype: int64

In [122]:
artists = pd.read_csv('../data_MoMa/artists.csv')
artists

       Artist ID             Name Nationality Gender  Birth Year  Death Year
0              1   Robert Arneson    American   Male      1930.0      1992.0
1              2   Doroteo Arnaiz     Spanish   Male      1936.0         NaN
2              3      Bill Arnold    American   Male      1941.0         NaN
3              4  Charles Arnoldi    American   Male      1946.0         NaN
4              5      Per Arnoldi      Danish   Male      1941.0         NaN
...          ...              ...         ...    ...         ...         ...
15086      67452      Liu Jianhua     Chinese   Male      1962.0         NaN
15087      67453         Leng Lin     Chinese   Male      1965.0         NaN
15088      67652     Ellie Nagler         NaN    NaN         NaN         NaN
15089      67694   Glenn Williams         NaN   Male         NaN         NaN
15090      67695        Ely Ramen         NaN    NaN         NaN         NaN

[15091 rows x 6 columns]

In [123]:
#check for null values
artists.isna().sum()

Artist ID          0
Name               0
Nationality     2488
Gender          3072
Birth Year      3854
Death Year     10512
dtype: int64

In [124]:
# import dataframe into sql

# define asking for password
password = getpass("Please enter your password: ")

Please enter your password: ········

In [125]:
def load_dataframe_to_mysql(df, database, table, username, password, host='localhost', port=3306):
    """
    Load a Pandas DataFrame into a MySQL database table.
    
    Parameters:
    df (pandas.DataFrame): 
    database (str): 
    table (str): 
    username (str): 
    password (str): 
    host (str, optional): The hostname or IP address of the MySQL server (default is 'localhost').
    port (int, optional): The port number to use to connect to the MySQL server (default is 3306).
    """
    
    # create a MySQL engine using sqlalchemy
    engine = create_engine(f'mysql://{username}:{password}@{host}:{port}/{database}')

    # write the dataframe to a SQL table
    df.to_sql(name=table, con=engine, if_exists='replace', index=False)

    # close the database connection
    engine.dispose()

In [126]:
load_dataframe_to_mysql(artworks, 'moma', 'artworks', 'root', password)

In [127]:
load_dataframe_to_mysql(artists, 'moma', 'artists', 'root', password)

In [128]:
dbName = "moma"

In [129]:
connectionData=f"mysql+pymysql://root:{password}@localhost/{dbName}"

In [130]:
engine = alch.create_engine(connectionData)

In [131]:
# join artworks + artists

artworks_artists = pd.read_sql_query("""

SELECT Title, Year, Department, Classification, Medium, `Acquisition Date`, artists.*
	FROM artworks
		JOIN artists
			ON artists.`Artist ID` = artworks.`Artist ID`;

""", engine)

artworks_artists

,Title,Year,Department,Classification,Medium,Acquisition Date,Artist ID,Name,Nationality,Gender,Birth Year,Death Year
0,"Earth-Cloud House, project",1970,Architecture & Design,Architecture,Graphite,1980-01-08,47,Raimund Abraham,American,Male,1933.0,2010.0
1,"Villa Snellman, Djursholm, Sweden, Elevation o...",1917,Architecture & Design,Architecture,Graphite and crayon on tracing paper mounted o...,1990-01-17,27,Erik Gunnar Asplund,Swedish,Male,1885.0,1940.0
2,"Villa Snellman, Djursholm, Sweden, Exterior el...",1917,Architecture & Design,Architecture,Ink on ozalid,1990-01-17,27,Erik Gunnar Asplund,Swedish,Male,1885.0,1940.0
3,"Villa Snellman, Djursholm, Sweden, Exterior el...",1917,Architecture & Design,Architecture,Ink on ozalid,1990-01-17,27,Erik Gunnar Asplund,Swedish,Male,1885.0,1940.0
4,"Villa Snellman, Djursholm, Sweden, Site plan",1917,Architecture & Design,Architecture,Graphite and crayon on tracing paper mounted o...,1990-01-17,27,Erik Gunnar Asplund,Swedish,Male,1885.0,1940.0
...,...,...,...,...,...,...,...,...,...,...,...,...
128797,Big Wack,1983,Film,Film,Super 8mm film,2016-10-18,67349,Julius Klein,American,None,1951.0,NaN
128798,Dig,1985,Film,Film,Super 8mm film,2016-10-18,67349,Julius Klein,American,None,1951.0,NaN
128799,Sylvester's Light,1984,Film,Video,Video,2016-10-18,67349,Julius Klein,American,None,1951.0,NaN
128800,M&A,2013,Media and Performance Art,Performance,"Performance, props, and algorithmic trading st...",2016-12-15,49568,GOLDIN + SENNEBY,Swedish,None,2004.0,NaN
128801,Portrait of Takako Saito,None,Prints & Illustrated Books,Photograph,Gelatin silver print,2008-10-08,21398,George Maciunas,American,Male,1931.0,1978.0

In [132]:
#convert Birth year and Death year to string
#artworks_artists['Birth Year'].astype(str)

artworks_artists['Birth Year'].isna().sum()

8157

In [133]:
artworks_artists['Birth Year'].astype(str)

0         1933.0
1         1885.0
2         1885.0
3         1885.0
4         1885.0
           ...
128797    1951.0
128798    1951.0
128799    1951.0
128800    2004.0
128801    1931.0
Name: Birth Year, Length: 128802, dtype: object

In [134]:
artworks_artists['Birth Year'] = artworks_artists['Birth Year'].apply(lambda x: str(x))

In [135]:
#extract date with regex, to get a clean year. first 4 digits only

artworks_artists['Birth Year'] = artworks_artists['Birth Year'].str.extract('(\d{4})')

In [136]:
artworks_artists['Death Year'] = artworks_artists['Death Year'].apply(lambda x: str(x))

In [137]:
#extract date with regex, to get a clean year. first 4 digits only

artworks_artists['Death Year'] = artworks_artists['Death Year'].str.extract('(\d{4})')

In [138]:
artworks_artists.Gender.unique()

array(['Male', None, 'Female', 'male'], dtype=object)

In [139]:
# edit Gender column
# new list with valid entries

F_M = ['Female', 'Male']

In [140]:
#rename to unknown if not Male or Female
artworks_artists.Gender = artworks_artists.Gender.apply(lambda x: 'unknown' if x not in F_M else x)

In [142]:
artworks_artists.Year = artworks_artists.Year.apply(lambda x: str(x))

In [143]:
artworks_artists

,Title,Year,Department,Classification,Medium,Acquisition Date,Artist ID,Name,Nationality,Gender,Birth Year,Death Year
0,"Earth-Cloud House, project",1970,Architecture & Design,Architecture,Graphite,1980-01-08,47,Raimund Abraham,American,Male,1933,2010
1,"Villa Snellman, Djursholm, Sweden, Elevation o...",1917,Architecture & Design,Architecture,Graphite and crayon on tracing paper mounted o...,1990-01-17,27,Erik Gunnar Asplund,Swedish,Male,1885,1940
2,"Villa Snellman, Djursholm, Sweden, Exterior el...",1917,Architecture & Design,Architecture,Ink on ozalid,1990-01-17,27,Erik Gunnar Asplund,Swedish,Male,1885,1940
3,"Villa Snellman, Djursholm, Sweden, Exterior el...",1917,Architecture & Design,Architecture,Ink on ozalid,1990-01-17,27,Erik Gunnar Asplund,Swedish,Male,1885,1940
4,"Villa Snellman, Djursholm, Sweden, Site plan",1917,Architecture & Design,Architecture,Graphite and crayon on tracing paper mounted o...,1990-01-17,27,Erik Gunnar Asplund,Swedish,Male,1885,1940
...,...,...,...,...,...,...,...,...,...,...,...,...
128797,Big Wack,1983,Film,Film,Super 8mm film,2016-10-18,67349,Julius Klein,American,unknown,1951,NaN
128798,Dig,1985,Film,Film,Super 8mm film,2016-10-18,67349,Julius Klein,American,unknown,1951,NaN
128799,Sylvester's Light,1984,Film,Video,Video,2016-10-18,67349,Julius Klein,American,unknown,1951,NaN
128800,M&A,2013,Media and Performance Art,Performance,"Performance, props, and algorithmic trading st...",2016-12-15,49568,GOLDIN + SENNEBY,Swedish,unknown,2004,NaN
128801,Portrait of Takako Saito,None,Prints & Illustrated Books,Photograph,Gelatin silver print,2008-10-08,21398,George Maciunas,American,Male,1931,1978

In [144]:
artworks_artists.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128802 entries, 0 to 128801
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Title             128766 non-null  object
 1   Year              128802 non-null  object
 2   Department        128802 non-null  object
 3   Classification    128802 non-null  object
 4   Medium            117233 non-null  object
 5   Acquisition Date  123494 non-null  object
 6   Artist ID         128802 non-null  int64
 7   Name              128802 non-null  object
 8   Nationality       124797 non-null  object
 9   Gender            128802 non-null  object
 10  Birth Year        120645 non-null  object
 11  Death Year        79675 non-null   object
dtypes: int64(1), object(11)
memory usage: 11.8+ MB

In [110]:
# save clean dataset
artworks_artists.to_csv("../data_MoMa/artworks_artists.csv", index=False)

In [111]:
# test if the file was saved correctly, by loading it
artworks_artists = pd.read_csv("../data_MoMa/artworks_artists.csv")
artworks_artists

,Title,Year,Department,Classification,Medium,Acquisition Date,Artist ID,Name,Nationality,Gender,Birth Year,Death Year
0,"Earth-Cloud House, project",1970.0,Architecture & Design,Architecture,Graphite,1980-01-08,47,Raimund Abraham,American,Male,1933.0,2010.0
1,"Villa Snellman, Djursholm, Sweden, Elevation o...",1917.0,Architecture & Design,Architecture,Graphite and crayon on tracing paper mounted o...,1990-01-17,27,Erik Gunnar Asplund,Swedish,Male,1885.0,1940.0
2,"Villa Snellman, Djursholm, Sweden, Exterior el...",1917.0,Architecture & Design,Architecture,Ink on ozalid,1990-01-17,27,Erik Gunnar Asplund,Swedish,Male,1885.0,1940.0
3,"Villa Snellman, Djursholm, Sweden, Exterior el...",1917.0,Architecture & Design,Architecture,Ink on ozalid,1990-01-17,27,Erik Gunnar Asplund,Swedish,Male,1885.0,1940.0
4,"Villa Snellman, Djursholm, Sweden, Site plan",1917.0,Architecture & Design,Architecture,Graphite and crayon on tracing paper mounted o...,1990-01-17,27,Erik Gunnar Asplund,Swedish,Male,1885.0,1940.0
...,...,...,...,...,...,...,...,...,...,...,...,...
128797,Big Wack,1983.0,Film,Film,Super 8mm film,2016-10-18,67349,Julius Klein,American,unknown,1951.0,NaN
128798,Dig,1985.0,Film,Film,Super 8mm film,2016-10-18,67349,Julius Klein,American,unknown,1951.0,NaN
128799,Sylvester's Light,1984.0,Film,Video,Video,2016-10-18,67349,Julius Klein,American,unknown,1951.0,NaN
128800,M&A,2013.0,Media and Performance Art,Performance,"Performance, props, and algorithmic trading st...",2016-12-15,49568,GOLDIN + SENNEBY,Swedish,unknown,2004.0,NaN
128801,Portrait of Takako Saito,NaN,Prints & Illustrated Books,Photograph,Gelatin silver print,2008-10-08,21398,George Maciunas,American,Male,1931.0,1978.0

In [ ]:
#not sure why the saved file converts Year to float ??